export const userSummaryCards = [
  {
    label: "Total Users",
    value: "1,248",
    helper: "",
    tone: "total",
  },
  {
    label: "Active Accounts",
    value: "1,102",
    helper: "can place orders",
    tone: "active",
  },
  {
    label: "New This Week",
    value: "84",
    helper: "",
    tone: "new",
  },
  {
    label: "Verified Students",
    value: "312",
    helper: "discount eligible",
    tone: "verified",
  },
  {
    label: "Open Issues",
    value: "12",
    helper: "needs attention",
    tone: "warning",
  },
];

export const userStatusFilters = [
  "All",
  "Active",
  "Suspended",
  "Deactivated",
];

export const studentStatusFilters = [
  "All verification statuses",
  "Verified",
  "Pending",
  "Not verified",
];

export const userIssueFilters = [
  "All issue states",
  "Has open issues",
  "No open issues",
  "Refund request",
  "Payment issue",
  "Open support ticket",
  "Late delivery complaint",
  "Verification issue",
];

export const usersMockData = [
  {
    id: "alex-carter",
    name: "Alex Carter",
    email: "alex.carter@email.com",
    phone: "+1 555 0182",
    joined: "May 12, 2026",
    isNew: false,
    status: "Active",
    studentStatus: "Verified",
    orders: 12,
    totalSpent: 286.4,
    lastOrder: "Today, 10:42 AM",
    primaryIssue: null,
    issues: [],
    recentOrders: [
      {
        id: "#1048",
        restaurant: "Burger House",
        total: 24.5,
        status: "Preparing",
      },
      {
        id: "#1031",
        restaurant: "Pizza Nova",
        total: 31.2,
        status: "Delivered",
      },
      {
        id: "#1018",
        restaurant: "Sushi Corner",
        total: 42.1,
        status: "Delivered",
      },
    ],
    discounts: [
      { name: "Student Deal", status: "Eligible" },
      { name: "WELCOME10", status: "Used" },
    ],
  },
  {
    id: "emma-brown",
    name: "Emma Brown",
    email: "emma.brown@email.com",
    phone: "+1 555 0134",
    joined: "Apr 28, 2026",
    isNew: false,
    status: "Active",
    studentStatus: "Not verified",
    orders: 8,
    totalSpent: 198.2,
    lastOrder: "Today, 10:39 AM",
    primaryIssue: "Refund request",
    issues: [
      {
        ticketId: "SUP-1047",
        type: "Refund request",
        detail: "Order #1041",
        status: "Open",
        priority: "Medium",
      },
    ],
    recentOrders: [
      {
        id: "#1047",
        restaurant: "Pizza Nova",
        total: 31.2,
        status: "On the way",
      },
      {
        id: "#1041",
        restaurant: "Green Bowl",
        total: 22.3,
        status: "Delivered",
      },
    ],
    discounts: [{ name: "WELCOME10", status: "Used" }],
  },
  {
    id: "david-kim",
    name: "David Kim",
    email: "david.kim@email.com",
    phone: "+1 555 0175",
    joined: "This week",
    isNew: true,
    status: "Active",
    studentStatus: "Pending",
    orders: 1,
    totalSpent: 18.9,
    lastOrder: "Today, 10:34 AM",
    primaryIssue: "Verification issue",
    issues: [
      {
        ticketId: "SUP-1046",
        type: "Verification issue",
        detail: "Student verification pending",
        status: "Open",
        priority: "Low",
      },
    ],
    recentOrders: [
      {
        id: "#1046",
        restaurant: "The Burger Lab",
        total: 18.9,
        status: "New",
      },
    ],
    discounts: [{ name: "Student Deal", status: "Pending verification" }],
  },
  {
    id: "sofia-miller",
    name: "Sofia Miller",
    email: "sofia.miller@email.com",
    phone: "+1 555 0191",
    joined: "Mar 18, 2026",
    isNew: false,
    status: "Active",
    studentStatus: "Verified",
    orders: 24,
    totalSpent: 642.1,
    lastOrder: "Today, 10:21 AM",
    primaryIssue: null,
    issues: [],
    recentOrders: [
      {
        id: "#1045",
        restaurant: "Sushi Corner",
        total: 42.1,
        status: "Delivered",
      },
      {
        id: "#1028",
        restaurant: "Burger House",
        total: 28.4,
        status: "Delivered",
      },
      {
        id: "#1019",
        restaurant: "Pasta Point",
        total: 31.6,
        status: "Delivered",
      },
    ],
    discounts: [
      { name: "Student Deal", status: "Eligible" },
      { name: "Lunch Promo", status: "Used" },
    ],
  },
  {
    id: "mia-wilson",
    name: "Mia Wilson",
    email: "mia.wilson@email.com",
    phone: "+1 555 0148",
    joined: "Feb 9, 2026",
    isNew: false,
    status: "Active",
    studentStatus: "Verified",
    orders: 16,
    totalSpent: 418.8,
    lastOrder: "Today, 10:14 AM",
    primaryIssue: "Late delivery complaint",
    issues: [
      {
        ticketId: "SUP-1044",
        type: "Late delivery complaint",
        detail: "Order #1044",
        status: "In progress",
        priority: "High",
      },
    ],
    recentOrders: [
      {
        id: "#1044",
        restaurant: "Pasta Point",
        total: 27.8,
        status: "On the way",
      },
      {
        id: "#1032",
        restaurant: "Taco Street",
        total: 16.4,
        status: "Delivered",
      },
    ],
    discounts: [{ name: "Student Deal", status: "Eligible" }],
  },
  {
    id: "noah-clark",
    name: "Noah Clark",
    email: "noah.clark@email.com",
    phone: "+1 555 0166",
    joined: "Jun 1, 2026",
    isNew: false,
    status: "Suspended",
    studentStatus: "Not verified",
    orders: 2,
    totalSpent: 42.7,
    lastOrder: "Yesterday",
    primaryIssue: "Payment issue",
    issues: [
      {
        ticketId: "SUP-1042",
        type: "Payment issue",
        detail: "Order #1042",
        status: "Open",
        priority: "High",
      },
    ],
    recentOrders: [
      {
        id: "#1042",
        restaurant: "Quick Bites",
        total: 12.9,
        status: "Cancelled",
      },
      {
        id: "#1022",
        restaurant: "Burger House",
        total: 29.8,
        status: "Failed payment",
      },
    ],
    discounts: [{ name: "No discounts used", status: "" }],
  },
  {
    id: "lily-adams",
    name: "Lily Adams",
    email: "lily.adams@email.com",
    phone: "+1 555 0189",
    joined: "Jan 22, 2026",
    isNew: false,
    status: "Active",
    studentStatus: "Verified",
    orders: 18,
    totalSpent: 512.3,
    lastOrder: "Yesterday",
    primaryIssue: "Open support ticket",
    issues: [
      {
        ticketId: "SUP-1041",
        type: "Open support ticket",
        detail: "Missing item",
        status: "Open",
        priority: "Medium",
      },
    ],
    recentOrders: [
      {
        id: "#1041",
        restaurant: "Green Bowl",
        total: 22.3,
        status: "Delivered",
      },
      {
        id: "#1030",
        restaurant: "Sushi Corner",
        total: 36.7,
        status: "Delivered",
      },
    ],
    discounts: [
      { name: "Student Deal", status: "Eligible" },
      { name: "WELCOME10", status: "Used" },
    ],
  },
  {
    id: "mark-king",
    name: "Mark King",
    email: "mark.king@email.com",
    phone: "+1 555 0127",
    joined: "Dec 4, 2025",
    isNew: false,
    status: "Deactivated",
    studentStatus: "Not verified",
    orders: 5,
    totalSpent: 96.4,
    lastOrder: "Jun 8",
    primaryIssue: null,
    issues: [],
    recentOrders: [
      {
        id: "#1039",
        restaurant: "Sushi Corner",
        total: 36.7,
        status: "Delivered",
      },
    ],
    discounts: [{ name: "No discounts used", status: "" }],
  },
  {
    id: "olivia-stone",
    name: "Olivia Stone",
    email: "olivia.stone@email.com",
    phone: "+1 555 0118",
    joined: "This week",
    isNew: true,
    status: "Active",
    studentStatus: "Pending",
    orders: 0,
    totalSpent: 0,
    lastOrder: "No orders yet",
    primaryIssue: "Verification issue",
    issues: [
      {
        ticketId: "SUP-1049",
        type: "Verification issue",
        detail: "Student verification pending",
        status: "Open",
        priority: "Low",
      },
    ],
    recentOrders: [],
    discounts: [{ name: "Student Deal", status: "Pending verification" }],
  },
  {
    id: "daniel-lee",
    name: "Daniel Lee",
    email: "daniel.lee@email.com",
    phone: "+1 555 0156",
    joined: "May 30, 2026",
    isNew: false,
    status: "Active",
    studentStatus: "Not verified",
    orders: 7,
    totalSpent: 174.6,
    lastOrder: "Jun 10",
    primaryIssue: null,
    issues: [],
    recentOrders: [
      {
        id: "#1038",
        restaurant: "Taco Street",
        total: 21.9,
        status: "Delivered",
      },
      {
        id: "#1024",
        restaurant: "Pizza Nova",
        total: 33.2,
        status: "Delivered",
      },
    ],
    discounts: [{ name: "WELCOME10", status: "Used" }],
  },
];
