export const restaurantCategoryFilters = [
  "All categories",
  "Burgers",
  "Pizza",
  "Sushi",
  "Mexican",
  "Italian",
  "Healthy",
  "Fast Food",
  "Desserts",
];

export const restaurantsMockData = [
  {
    id: "burger-house",
    name: "Burger House",
    cuisine: "Burgers",
    rating: 4.8,
    status: "Active",
    issue: null,
    deliveryTime: "25-35 min",
    menuItems: 24,
    ordersToday: 42,
    location: "Downtown",
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&q=80",
  },
  {
    id: "pizza-nova",
    name: "Pizza Nova",
    cuisine: "Pizza",
    rating: 4.6,
    status: "Active",
    issue: null,
    deliveryTime: "30-40 min",
    menuItems: 18,
    ordersToday: 31,
    location: "Market Street",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=200&q=80",
  },
  {
    id: "the-burger-lab",
    name: "The Burger Lab",
    cuisine: "Burgers",
    rating: 4.7,
    status: "Active",
    issue: "Low availability",
    deliveryTime: "20-30 min",
    menuItems: 21,
    ordersToday: 36,
    location: "King Street",
    image:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?w=200&q=80",
  },
  {
    id: "sushi-corner",
    name: "Sushi Corner",
    cuisine: "Sushi",
    rating: 4.5,
    status: "Paused",
    issue: "Many cancellations",
    deliveryTime: "35-45 min",
    menuItems: 32,
    ordersToday: 24,
    location: "Harbor Road",
    image:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=200&q=80",
  },
  {
    id: "green-bowl",
    name: "Green Bowl",
    cuisine: "Healthy",
    rating: null,
    status: "Pending",
    issue: "Missing documents",
    deliveryTime: "25-35 min",
    menuItems: 12,
    ordersToday: 0,
    location: "Garden Walk",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=200&q=80",
  },
  {
    id: "taco-street",
    name: "Taco Street",
    cuisine: "Mexican",
    rating: 4.4,
    status: "Active",
    issue: null,
    deliveryTime: "20-30 min",
    menuItems: 16,
    ordersToday: 28,
    location: "Sunset Court",
    image:
      "https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=200&q=80",
  },
  {
    id: "quick-bites",
    name: "Quick Bites",
    cuisine: "Fast Food",
    rating: 4.2,
    status: "Paused",
    issue: "Missing menu images",
    deliveryTime: "15-25 min",
    menuItems: 14,
    ordersToday: 7,
    location: "Oak Drive",
    image:
      "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=200&q=80",
  },
  {
    id: "pasta-point",
    name: "Pasta Point",
    cuisine: "Italian",
    rating: null,
    status: "Rejected",
    issue: "Missing documents",
    deliveryTime: "-",
    menuItems: 10,
    ordersToday: 0,
    location: "Old Town",
    image:
      "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=200&q=80",
  },
];

export const menuItemsMockData = [
  {
    id: "classic-cheeseburger",
    name: "Classic Cheeseburger",
    restaurant: "Burger House",
    category: "Burgers",
    price: 9,
    availability: "Available",
    discount: null,
    ordersToday: 45,
    calories: "780 kcal",
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=160&q=80",
  },
  {
    id: "signature-truffle-burger",
    name: "Signature Truffle Burger",
    restaurant: "The Burger Lab",
    category: "Burgers",
    price: 12.5,
    availability: "Available",
    discount: "10% off",
    ordersToday: 32,
    calories: "850 kcal",
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=160&q=80",
  },
  {
    id: "double-cheese-bbq",
    name: "Double Cheese BBQ",
    restaurant: "Burger House",
    category: "Burgers",
    price: 10.5,
    availability: "Available",
    discount: null,
    ordersToday: 28,
    calories: "950 kcal",
    image:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?w=160&q=80",
  },
  {
    id: "fries",
    name: "Fries",
    restaurant: "Burger House",
    category: "Sides",
    price: 4.5,
    availability: "Unavailable",
    discount: null,
    ordersToday: 0,
    calories: "420 kcal",
    image: "",
  },
  {
    id: "coke",
    name: "Coke",
    restaurant: "Burger House",
    category: "Drinks",
    price: 2,
    availability: "Available",
    discount: null,
    ordersToday: 19,
    calories: "140 kcal",
    image:
      "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=160&q=80",
  },
  {
    id: "margherita-pizza",
    name: "Margherita Pizza",
    restaurant: "Pizza Nova",
    category: "Pizza",
    price: 11.5,
    availability: "Available",
    discount: null,
    ordersToday: 31,
    calories: "920 kcal",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=160&q=80",
  },
  {
    id: "salmon-roll",
    name: "Salmon Roll",
    restaurant: "Sushi Corner",
    category: "Sushi",
    price: 13,
    availability: "Available",
    discount: null,
    ordersToday: 24,
    calories: "450 kcal",
    image:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=160&q=80",
  },
  {
    id: "chicken-pasta",
    name: "Chicken Pasta",
    restaurant: "Pasta Point",
    category: "Pasta",
    price: 12,
    availability: "Unavailable",
    discount: null,
    ordersToday: 0,
    calories: "780 kcal",
    image:
      "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=160&q=80",
  },
  {
    id: "spicy-chicken-wrap",
    name: "Spicy Chicken Wrap",
    restaurant: "Taco Street",
    category: "Mexican",
    price: 8.9,
    availability: "Available",
    discount: "15% off",
    ordersToday: 22,
    calories: "610 kcal",
    image:
      "https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=160&q=80",
  },
  {
    id: "green-bowl-salad",
    name: "Green Bowl Salad",
    restaurant: "Green Bowl",
    category: "Salads",
    price: 9.8,
    availability: "Available",
    discount: null,
    ordersToday: 14,
    calories: "350 kcal",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=160&q=80",
  },
];
