export const financePromotionsMockData = [
  {
    name: "WELCOME10",
    code: "WELCOME10",
    type: "Promo code",
    funding: "Platform-funded",
    restaurant: null,
    value: "10% off",
    audience: "New users",
    status: "Active",
    usageToday: 18,
    usageTotal: 240,
    costToday: "$42 platform",
    validity: "Jun 1 — Jun 30",
    startDate: "Jun 1, 2026",
    endDate: "Jun 30, 2026",
    minimumOrder: "—",
    maximumDiscount: "$10",
    totalBudget: 300,
    spentBudget: 96,
    redemptionLimit: 500,
    platformFunding: 96,
    restaurantFunding: 0,
    createdBy: "Admin Team",
    createdDate: "May 28, 2026",
  },
  {
    name: "STUDENT15",
    code: "STUDENT15",
    type: "Student deal",
    funding: "Platform-funded",
    restaurant: null,
    value: "15% off",
    audience: "Verified students",
    status: "Active",
    usageToday: 12,
    usageTotal: 180,
    costToday: "$36 platform",
    validity: "Always active",
    startDate: "Always active",
    endDate: "—",
    minimumOrder: "—",
    maximumDiscount: "$12",
    totalBudget: 450,
    spentBudget: 168,
    redemptionLimit: 600,
    platformFunding: 168,
    restaurantFunding: 0,
    createdBy: "Growth Team",
    createdDate: "May 12, 2026",
  },
  {
    name: "BURGER20",
    code: "BURGER20",
    type: "Restaurant offer",
    funding: "Restaurant-funded",
    restaurant: "Burger House",
    value: "20% off",
    audience: "Burger House customers",
    status: "Active",
    usageToday: 9,
    usageTotal: 96,
    costToday: "$18 restaurant",
    validity: "Jun 10 — Jun 24",
    startDate: "Jun 10, 2026",
    endDate: "Jun 24, 2026",
    minimumOrder: "—",
    maximumDiscount: "$8",
    totalBudget: 220,
    spentBudget: 82,
    redemptionLimit: 250,
    platformFunding: 0,
    restaurantFunding: 82,
    createdBy: "Burger House",
    createdDate: "Jun 7, 2026",
  },
  {
    name: "FREESHIP",
    code: "FREESHIP",
    type: "Free delivery",
    funding: "Shared",
    restaurant: null,
    value: "Free delivery",
    audience: "Orders over $25",
    status: "Active",
    usageToday: 7,
    usageTotal: 140,
    costToday: "$24 shared",
    validity: "Jun 5 — Jun 18",
    startDate: "Jun 5, 2026",
    endDate: "Jun 18, 2026",
    minimumOrder: "$25",
    maximumDiscount: "Delivery fee",
    totalBudget: 300,
    spentBudget: 124,
    redemptionLimit: 400,
    platformFunding: 62,
    restaurantFunding: 62,
    periodPlatformFunding: 12,
    periodRestaurantFunding: 12,
    createdBy: "Admin Team",
    createdDate: "Jun 2, 2026",
  },
  {
    name: "LUNCHDEAL",
    code: "LUNCHDEAL",
    type: "Seasonal campaign",
    funding: "Shared",
    restaurant: null,
    value: "$5 off",
    audience: "Lunch orders",
    status: "Scheduled",
    usageToday: 0,
    usageTotal: 0,
    costToday: "$0",
    validity: "Starts Jun 20",
    startDate: "Jun 20, 2026",
    endDate: "Jul 15, 2026",
    minimumOrder: "$15",
    maximumDiscount: "$5",
    totalBudget: 500,
    spentBudget: 0,
    redemptionLimit: 500,
    platformFunding: 250,
    restaurantFunding: 250,
    periodPlatformFunding: 0,
    periodRestaurantFunding: 0,
    createdBy: "Growth Team",
    createdDate: "Jun 12, 2026",
  },
  {
    name: "PIZZA5",
    code: "PIZZA5",
    type: "Restaurant offer",
    funding: "Restaurant-funded",
    restaurant: "Pizza Nova",
    value: "$5 off",
    audience: "Pizza Nova customers",
    status: "Paused",
    usageToday: 0,
    usageTotal: 88,
    costToday: "$0",
    validity: "Jun 1 — Jun 28",
    startDate: "Jun 1, 2026",
    endDate: "Jun 28, 2026",
    minimumOrder: "$25",
    maximumDiscount: "$5",
    totalBudget: 180,
    spentBudget: 74,
    redemptionLimit: 200,
    platformFunding: 0,
    restaurantFunding: 74,
    createdBy: "Pizza Nova",
    createdDate: "May 27, 2026",
  },
  {
    name: "WELCOMEFOOD",
    code: "WELCOMEFOOD",
    type: "Promo code",
    funding: "Platform-funded",
    restaurant: null,
    value: "$8 off",
    audience: "New users",
    status: "Expired",
    usageToday: 0,
    usageTotal: 184,
    costToday: "$0",
    validity: "Expired Jun 5",
    startDate: "May 1, 2026",
    endDate: "Jun 5, 2026",
    minimumOrder: "$20",
    maximumDiscount: "$8",
    totalBudget: 800,
    spentBudget: 736,
    redemptionLimit: 700,
    platformFunding: 736,
    restaurantFunding: 0,
    createdBy: "Growth Team",
    createdDate: "Apr 24, 2026",
  },
];
