export const SPECIAL_FILTERS = [
  { key: "All", labelKey: "specials.filters.all" },
  { key: "Free Delivery", labelKey: "specials.filters.freeDelivery" },
  { key: "Student Deals", labelKey: "specials.filters.studentDeals" },
  { key: "Lunch Combos", labelKey: "specials.filters.lunchCombos" },
  { key: "Family Sets", labelKey: "specials.filters.familySets" },
  { key: "New Restaurants", labelKey: "specials.filters.newRestaurants" },
  { key: "Limited Time", labelKey: "specials.filters.limitedTime" },
  { key: "Best Value", labelKey: "specials.filters.bestValue" },
];

export const DEALS = [
  {
    id: 1,
    titleKey: "specials.deals.burgers.title",
    descriptionKey: "specials.deals.burgers.description",
    categoryKey: "specials.deals.burgers.category",
    restaurantKey: "specials.deals.burgers.restaurant",
    category: "Free Delivery",
    filterCategory: "Free Delivery",
    price: "15",
    weight: "750g",
    calories: "850 kcal",
    rating: 4.8,
    reviews: 400,
    imageUrl: "/img/burger.jpg",
  },
  {
    id: 2,
    titleKey: "specials.deals.sushi.title",
    descriptionKey: "specials.deals.sushi.description",
    categoryKey: "specials.deals.sushi.category",
    restaurantKey: "specials.deals.sushi.restaurant",
    category: "Limited Time",
    filterCategory: "Limited Time",
    price: "19.99",
    weight: "800g",
    calories: "650 kcal",
    rating: 4.9,
    reviews: 630,
    imageUrl:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80",
  },
  {
    id: 3,
    titleKey: "specials.deals.student.title",
    descriptionKey: "specials.deals.student.description",
    categoryKey: "specials.deals.student.category",
    restaurantKey: "specials.deals.student.restaurant",
    category: "Student Deal",
    filterCategory: "Student Deals",
    price: "9.99",
    weight: "450g",
    calories: "350 kcal",
    rating: 4.7,
    reviews: 400,
    imageUrl:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
  },
  {
    id: 4,
    titleKey: "specials.deals.pizza.title",
    descriptionKey: "specials.deals.pizza.description",
    categoryKey: "specials.deals.pizza.category",
    restaurantKey: "specials.deals.pizza.restaurant",
    category: "Limited Time",
    filterCategory: "Limited Time",
    price: "17.99",
    weight: "900g",
    calories: "1200 kcal",
    rating: 4.8,
    reviews: 215,
    imageUrl:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 5,
    titleKey: "specials.deals.family.title",
    descriptionKey: "specials.deals.family.description",
    categoryKey: "specials.deals.family.category",
    restaurantKey: "specials.deals.family.restaurant",
    category: "Family Sets",
    filterCategory: "Family Sets",
    price: "34.99",
    weight: "1.8kg",
    calories: "2100 kcal",
    rating: 4.7,
    reviews: 180,
    imageUrl: "/img/china_ma.jpg",
  },
  {
    id: 6,
    titleKey: "specials.deals.sweet.title",
    descriptionKey: "specials.deals.sweet.description",
    categoryKey: "specials.deals.sweet.category",
    restaurantKey: "specials.deals.sweet.restaurant",
    category: "Best Value",
    filterCategory: "Best Value",
    price: "12.50",
    weight: "600g",
    calories: "980 kcal",
    rating: 4.9,
    reviews: 310,
    imageUrl:
      "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&q=80",
  },
];

export const SPECIAL_STEPS = [
  {
    titleKey: "specials.steps.choose.title",
    textKey: "specials.steps.choose.text",
  },
  {
    titleKey: "specials.steps.cart.title",
    textKey: "specials.steps.cart.text",
  },
  {
    titleKey: "specials.steps.enjoy.title",
    textKey: "specials.steps.enjoy.text",
  },
];
