export const financeDateFilters = [
  "Today",
  "Yesterday",
  "Last 7 days",
  "Last 30 days",
  "This month",
  "Custom range",
];

export const financeSummaryCards = [
  {
    label: "Gross Revenue",
    value: "$2,430",
    helper: "+8.4%",
    tone: "success",
  },
  {
    label: "Net Platform Revenue",
    value: "$268",
    helper: "+6.2%",
    tone: "fees",
  },
  {
    label: "Restaurant Payouts",
    value: "$1,820",
    helper: "Updated",
    tone: "payouts",
  },
  {
    label: "Refunds",
    value: "$120",
    helper: "+3.2%",
    tone: "refunds",
  },
  {
    label: "Platform Promo Cost",
    value: "$96",
    helper: "-4.1%",
    tone: "success",
  },
];

export const financeOverviewData = {
  revenueTrend: [
    {
      label: "Apr 15",
      grossRevenue: 7840,
      restaurantPayouts: 5880,
      estimatedPlatformFees: 1176,
      netPlatformRevenue: 966,
      refunds: 280,
      platformPromoCost: 210,
    },
    {
      label: "Apr 22",
      grossRevenue: 8120,
      restaurantPayouts: 6090,
      estimatedPlatformFees: 1218,
      netPlatformRevenue: 978,
      refunds: 310,
      platformPromoCost: 240,
    },
    {
      label: "Apr 29",
      grossRevenue: 7760,
      restaurantPayouts: 5820,
      estimatedPlatformFees: 1164,
      netPlatformRevenue: 944,
      refunds: 260,
      platformPromoCost: 220,
    },
    {
      label: "May 6",
      grossRevenue: 8540,
      restaurantPayouts: 6405,
      estimatedPlatformFees: 1281,
      netPlatformRevenue: 1021,
      refunds: 340,
      platformPromoCost: 260,
    },
    {
      label: "May 13",
      grossRevenue: 8980,
      restaurantPayouts: 6735,
      estimatedPlatformFees: 1347,
      netPlatformRevenue: 1057,
      refunds: 390,
      platformPromoCost: 290,
    },
    {
      label: "May 20",
      grossRevenue: 8420,
      restaurantPayouts: 6315,
      estimatedPlatformFees: 1263,
      netPlatformRevenue: 1013,
      refunds: 300,
      platformPromoCost: 250,
    },
    {
      label: "May 27",
      grossRevenue: 9160,
      restaurantPayouts: 6870,
      estimatedPlatformFees: 1374,
      netPlatformRevenue: 1064,
      refunds: 420,
      platformPromoCost: 310,
    },
    {
      label: "Jun 3",
      grossRevenue: 9480,
      restaurantPayouts: 7110,
      estimatedPlatformFees: 1422,
      netPlatformRevenue: 1092,
      refunds: 360,
      platformPromoCost: 330,
    },
    {
      label: "Jun 10",
      grossRevenue: 8960,
      restaurantPayouts: 6720,
      estimatedPlatformFees: 1344,
      netPlatformRevenue: 1044,
      refunds: 410,
      platformPromoCost: 300,
    },
    {
      label: "Jun 17",
      grossRevenue: 9720,
      restaurantPayouts: 7290,
      estimatedPlatformFees: 1458,
      netPlatformRevenue: 1108,
      refunds: 450,
      platformPromoCost: 350,
    },
    {
      label: "Jun 24",
      grossRevenue: 9360,
      restaurantPayouts: 7020,
      estimatedPlatformFees: 1404,
      netPlatformRevenue: 1084,
      refunds: 380,
      platformPromoCost: 320,
    },
    {
      label: "Current",
      grossRevenue: 9880,
      restaurantPayouts: 7410,
      estimatedPlatformFees: 1482,
      netPlatformRevenue: 1098,
      refunds: 480,
      platformPromoCost: 384,
    },
  ],
  moneyFlow: {
    grossRevenue: 2430,
    estimatedPlatformFees: 364,
    restaurantPayouts: 1820,
    refunds: 120,
    platformPromoCost: 96,
  },
  attentionItems: [
    {
      label: "Failed payments",
      value: "3",
      actionLabel: "View transactions",
      description: "2 are eligible for a safe payment retry.",
      urgency: "High priority",
      shortcutKey: "failedPayments",
    },
    {
      label: "Pending refunds",
      value: "4",
      actionLabel: "Review refunds",
      description: "1 request has waited longer than 60 minutes.",
      urgency: "Review overdue",
      shortcutKey: "pendingRefunds",
    },
    {
      label: "Payouts on hold",
      value: "2",
      actionLabel: "Resolve payouts",
      description: "Restaurant verification is required.",
      urgency: "Action required",
      shortcutKey: "payoutsOnHold",
    },
    {
      label: "Expiring promotions",
      value: "1",
      actionLabel: "Open promotions",
      description: "Budget or end date requires attention.",
      urgency: "Ends soon",
      shortcutKey: "expiredPromotions",
    },
  ],
  topRestaurants: [
    { name: "Burger House", gross: 820, platformFee: 123, share: 33.7, change: 12 },
    { name: "The Burger Lab", gross: 690, platformFee: 104, share: 28.4, change: 8 },
    { name: "Pizza Nova", gross: 540, platformFee: 81, share: 22.2, change: -3 },
    { name: "Sushi Corner", gross: 410, platformFee: 62, share: 16.9, change: 5 },
  ],
  promotionImpact: {
    redemptionsToday: 46,
    platformPromoCost: 96,
    topPromo: "WELCOME10",
    refundsToday: 120,
    pendingRefunds: 4,
    topRefundReason: "Missing item",
    previousPeriodChange: 12,
  },
};

export const financeTabs = [
  "Overview",
  "Transactions",
  "Payouts",
  "Refunds",
  "Promotions",
];

export const transactionStatusFilters = [
  "All",
  "Paid",
  "Pending",
  "Failed",
  "Refunded",
  "Partially refunded",
];

export const payoutStatusFilters = [
  "All",
  "Pending",
  "Scheduled",
  "Paid",
  "On hold",
  "Failed",
];

export const refundStatusFilters = [
  "All",
  "Requested",
  "Processing",
  "Completed",
  "Rejected",
];

export const refundReasonFilters = [
  "All reasons",
  "Missing item",
  "Late delivery",
  "Payment issue",
  "Wrong item",
  "Cancelled order",
];

export const refundTypeFilters = ["All refund types", "Full refund", "Partial refund"];

export const transactionPaymentMethodFilters = [
  "All payment methods",
  "Card",
  "Apple Pay",
  "Google Pay",
];

export const promotionStatusFilters = [
  "All",
  "Active",
  "Scheduled",
  "Paused",
  "Expired",
];

export const promotionTypeFilters = [
  "All types",
  "Promo code",
  "Student deal",
  "Restaurant offer",
  "Free delivery",
  "Seasonal campaign",
];

export const promotionAudienceFilters = [
  "All audiences",
  "All users",
  "New users",
  "Verified students",
  "Restaurant customers",
  "Orders over $25",
];

export const financeTransactionsMockData = [
  {
    transactionId: "TXN-1048",
    orderId: "#1048",
    orderStatus: "Preparing",
    customer: "Alex Carter",
    restaurant: "Burger House",
    total: 24.5,
    platformFee: 3.7,
    restaurantPayout: 20.8,
    status: "Paid",
    paymentMethod: "Card",
    time: "Today, 10:42 AM",
    fullTimestamp: "Jul 13, 2026, 10:42:18 AM",
    processorReference: "pi_1048_DFL",
    refundedAmount: 0,
    timeline: ["10:42 AM — Payment created", "10:42 AM — Payment confirmed"],
  },
  {
    transactionId: "TXN-1047",
    orderId: "#1047",
    orderStatus: "On the way",
    customer: "Emma Brown",
    restaurant: "Pizza Nova",
    total: 31.2,
    platformFee: 4.7,
    restaurantPayout: 26.5,
    status: "Paid",
    paymentMethod: "Apple Pay",
    time: "Today, 10:39 AM",
    fullTimestamp: "Jul 13, 2026, 10:39:06 AM",
    processorReference: "pi_1047_DFL",
    refundedAmount: 0,
    timeline: ["10:39 AM — Payment created", "10:39 AM — Payment confirmed"],
  },
  {
    transactionId: "TXN-1046",
    orderId: "#1046",
    orderStatus: "New",
    customer: "David Kim",
    restaurant: "The Burger Lab",
    total: 18.9,
    platformFee: 2.8,
    restaurantPayout: 16.1,
    status: "Pending",
    paymentMethod: "Card",
    time: "Today, 10:34 AM",
    fullTimestamp: "Jul 13, 2026, 10:34:41 AM",
    processorReference: "pi_1046_DFL",
    refundedAmount: 0,
    timeline: ["10:34 AM — Payment created", "10:35 AM — Waiting confirmation"],
  },
  {
    transactionId: "TXN-1045",
    orderId: "#1045",
    orderStatus: "Delivered",
    customer: "Sofia Miller",
    restaurant: "Sushi Corner",
    total: 42.1,
    platformFee: 6.3,
    restaurantPayout: 35.8,
    status: "Paid",
    paymentMethod: "Card",
    time: "Today, 10:21 AM",
    fullTimestamp: "Jul 13, 2026, 10:21:33 AM",
    processorReference: "pi_1045_DFL",
    refundedAmount: 0,
    timeline: ["10:21 AM — Payment created", "10:21 AM — Payment confirmed"],
  },
  {
    transactionId: "TXN-1042",
    orderId: "#1042",
    orderStatus: "Cancelled",
    customer: "Noah Clark",
    restaurant: "Quick Bites",
    total: 12.9,
    platformFee: 0,
    restaurantPayout: 0,
    status: "Failed",
    paymentMethod: "Card",
    time: "Today, 9:58 AM",
    fullTimestamp: "Jul 13, 2026, 9:58:09 AM",
    processorReference: "pi_1042_DFL",
    failureReason: "Issuer declined the payment. Retry is available.",
    refundedAmount: 0,
    timeline: ["9:58 AM — Payment created", "9:58 AM — Payment failed"],
  },
  {
    transactionId: "TXN-1041",
    orderId: "#1041",
    orderStatus: "Delivered",
    customer: "Lily Adams",
    restaurant: "Green Bowl",
    total: 22.3,
    platformFee: 3.3,
    restaurantPayout: 19,
    status: "Refunded",
    paymentMethod: "Card",
    time: "Yesterday",
    fullTimestamp: "Jul 12, 2026, 6:14:27 PM",
    processorReference: "pi_1041_DFL",
    refundedAmount: 22.3,
    timeline: ["Yesterday — Payment confirmed", "Today — Refund requested"],
  },
];

export const financePayoutsMockData = [
  {
    restaurant: "Burger House",
    period: "Today",
    orders: 42,
    grossSales: 820,
    platformFee: 123,
    restaurantPromoShare: 24,
    restaurantCoveredRefunds: 0,
    netPayout: 673,
    status: "Scheduled",
    expectedDate: "Today at 4:00 PM",
    paidDate: null,
    timeline: ["9:00 AM — Payout calculated", "4:00 PM — Scheduled transfer"],
  },
  {
    restaurant: "The Burger Lab",
    period: "Today",
    orders: 36,
    grossSales: 690,
    platformFee: 104,
    restaurantPromoShare: 18,
    restaurantCoveredRefunds: 0,
    netPayout: 568,
    status: "Pending",
    expectedDate: "Today at 5:00 PM",
    paidDate: null,
    timeline: ["9:00 AM — Payout calculated", "10:15 AM — Awaiting review"],
  },
  {
    restaurant: "Pizza Nova",
    period: "Today",
    orders: 31,
    grossSales: 540,
    platformFee: 81,
    restaurantPromoShare: 0,
    restaurantCoveredRefunds: 0,
    netPayout: 459,
    status: "Paid",
    expectedDate: "Jun 30, 2026",
    paidDate: "Jun 30 at 4:08 PM",
    timeline: ["Jun 30, 4:00 PM — Transfer started", "Jun 30, 4:08 PM — Paid"],
  },
  {
    restaurant: "Sushi Corner",
    period: "Today",
    orders: 24,
    grossSales: 410,
    platformFee: 62,
    restaurantPromoShare: 12,
    restaurantCoveredRefunds: 0,
    netPayout: 336,
    status: "On hold",
    expectedDate: "Delayed",
    paidDate: null,
    holdReason: "Restaurant verification required",
    timeline: ["9:00 AM — Payout calculated", "9:18 AM — Placed on hold"],
  },
  {
    restaurant: "Green Bowl",
    period: "Today",
    orders: 14,
    grossSales: 260,
    platformFee: 39,
    restaurantPromoShare: 0,
    restaurantCoveredRefunds: 22.3,
    netPayout: 198.7,
    status: "Failed",
    expectedDate: "Retry required",
    paidDate: null,
    failureReason: "Bank rejected the transfer",
    timeline: ["9:00 AM — Payout calculated", "11:03 AM — Bank rejected transfer"],
  },
];

export const financeRefundsMockData = [
  {
    refundId: "REF-1041",
    orderId: "#1041",
    restaurant: "Green Bowl",
    customer: "Lily Adams",
    amount: 22.3,
    reason: "Missing item",
    status: "Requested",
    impact: "Restaurant-covered",
    priority: "Medium",
    requested: "Today, 10:50 AM",
    refundType: "Full refund",
    requestAge: "18 min",
    overdue: false,
    customerDescription: "One paid item was missing from the delivered order.",
    orderItems: ["Green Bowl × 1", "Sparkling water × 1"],
    supportCase: "SUP-2041",
    timeline: [
      "10:50 AM — Refund requested",
      "10:52 AM — Waiting for admin review",
    ],
  },
  {
    refundId: "REF-1044",
    orderId: "#1044",
    restaurant: "Pasta Point",
    customer: "Mia Wilson",
    amount: 8,
    reason: "Late delivery",
    status: "Processing",
    impact: "Shared",
    priority: "High",
    requested: "Today, 10:24 AM",
    refundType: "Partial refund",
    requestAge: "1h 24m",
    overdue: true,
    customerDescription: "Delivery arrived after the promised window.",
    orderItems: ["Pasta Carbonara × 1"],
    supportCase: "SUP-2044",
    timeline: ["10:24 AM — Refund requested", "10:31 AM — Processing"],
  },
  {
    refundId: "REF-1042",
    orderId: "#1042",
    restaurant: "Quick Bites",
    customer: "Noah Clark",
    amount: 12.9,
    reason: "Payment issue",
    status: "Completed",
    impact: "Platform-covered",
    priority: "High",
    requested: "Today, 9:58 AM",
    refundType: "Full refund",
    requestAge: "2h 10m",
    overdue: false,
    customerDescription: "Payment completed after the order was cancelled.",
    orderItems: ["Quick lunch combo × 1"],
    supportCase: "SUP-2042",
    timeline: ["9:58 AM — Payment failed", "10:05 AM — Refund completed"],
  },
  {
    refundId: "REF-1037",
    orderId: "#1037",
    restaurant: "Pizza Nova",
    customer: "Emma Brown",
    amount: 15,
    reason: "Wrong item",
    status: "Rejected",
    impact: "Restaurant-covered",
    priority: "Low",
    requested: "Yesterday",
    refundType: "Partial refund",
    requestAge: "Yesterday",
    overdue: false,
    customerDescription: "Customer reported receiving the wrong side dish.",
    orderItems: ["Pepperoni Pizza × 1", "Garlic dip × 1"],
    supportCase: "SUP-2037",
    rejectionReason: "Restaurant photo confirmed the correct items were packed.",
    timeline: ["Yesterday — Refund requested", "Yesterday — Request rejected"],
  },
];

export { financePromotionsMockData } from "../shared/promotions.data.js";
