export const ACCOUNT_SECTIONS = [
  { id: "dashboard", label: "Dashboard" },
  { id: "orders", label: "Orders" },
  { id: "favorites", label: "Favorites" },
  { id: "addresses", label: "Addresses" },
  { id: "payments", label: "Payments & Discounts" },
  { id: "settings", label: "Settings" },
];

export const ORDER_FILTERS = [
  "All",
  "Active",
  "Delivered",
  "Cancelled",
  "Refunded",
];

export const MOCK_ACCOUNT = {
  user: {
    id: "denus",
    name: "Denus Korguc",
    email: "korguc5@gmail.com",
    phone: "+380 XX XXX XX XX",
    studentDiscountActive: true,
    defaultAddressId: "home",
  },
  dashboardStats: [
    { label: "Total Orders", value: "24", detail: "+3 this month" },
    { label: "Spent This Month", value: "$186.40", detail: "Across 7 orders" },
    { label: "Favorite Restaurant", value: "Kyoto Sushi & Wok", detail: "Ordered 6 times" },
    { label: "Saved Favorites", value: "8", detail: "Places and dishes" },
  ],
  activeOrder: {
    id: "DF-2048",
    restaurantName: "Kyoto Sushi & Wok",
    status: "active",
    statusLabel: "On the way",
    message: "Courier is heading to your address.",
    etaMinutes: 18,
    courierName: "Alex",
    deliveryAddress: "Green Park Area",
    progressSteps: ["Confirmed", "Preparing", "On the way", "Delivered"],
    activeStep: "On the way",
  },
  orders: [
    {
      id: "DF-2048",
      restaurantName: "Kyoto Sushi & Wok",
      status: "active",
      statusLabel: "On the way",
      date: "Today",
      time: "18:14",
      items: [
        {
          id: "kyoto-set",
          name: "Kyoto Sushi Set",
          price: 29.99,
          restaurant: "Kyoto Sushi & Wok",
          category: "Asian",
          image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500&q=80",
        },
        {
          id: "miso-soup",
          name: "Miso Soup",
          price: 5.5,
          restaurant: "Kyoto Sushi & Wok",
          category: "Asian",
          image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&q=80",
        },
      ],
      total: 35.49,
      address: "12 Green Park Area, Apt. 48",
      paymentMethod: "Visa ending in 4821",
      priceBreakdown: {
        subtotal: 35.49,
        delivery: 2.99,
        discount: 4,
        total: 34.48,
      },
    },
    {
      id: "DF-2035",
      restaurantName: "The Burger Joint",
      status: "delivered",
      statusLabel: "Delivered",
      date: "May 24",
      time: "18:42",
      items: [
        {
          id: "truffle-burger",
          name: "Signature Truffle Burger",
          price: 14.99,
          restaurant: "The Burger Joint",
          category: "Fast Food",
          image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&q=80",
        },
        {
          id: "fries",
          name: "Fries",
          price: 4.99,
          restaurant: "The Burger Joint",
          category: "Fast Food",
          image: "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=500&q=80",
        },
        {
          id: "cola",
          name: "Cola",
          price: 2.99,
          restaurant: "The Burger Joint",
          category: "Beverages",
          image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&q=80",
        },
      ],
      total: 24.99,
      address: "12 Green Park Area, Apt. 48",
      paymentMethod: "Visa ending in 4821",
      priceBreakdown: {
        subtotal: 22.97,
        delivery: 2,
        discount: 0,
        total: 24.97,
      },
    },
    {
      id: "DF-2029",
      restaurantName: "Fresh Poke Bowls",
      status: "cancelled",
      statusLabel: "Cancelled",
      date: "May 19",
      time: "12:20",
      items: [
        {
          id: "salmon-poke",
          name: "Salmon Poke Bowl",
          price: 16.5,
          restaurant: "Fresh Poke Bowls",
          category: "Healthy",
          image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&q=80",
        },
      ],
      total: 16.5,
      address: "Main Campus, Building B",
      paymentMethod: "Apple Pay",
      priceBreakdown: {
        subtotal: 16.5,
        delivery: 0,
        discount: 0,
        total: 0,
      },
    },
    {
      id: "DF-2018",
      restaurantName: "Luigi's Woodfire",
      status: "refunded",
      statusLabel: "Refunded",
      date: "May 08",
      time: "20:05",
      items: [
        {
          id: "pizza-amiza",
          name: "Pizza Amiza",
          price: 17.99,
          restaurant: "Luigi's Woodfire",
          category: "European",
          image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&q=80",
        },
      ],
      total: 17.99,
      address: "Business Center, Floor 4",
      paymentMethod: "Visa ending in 4821",
      priceBreakdown: {
        subtotal: 17.99,
        delivery: 2.99,
        discount: 0,
        total: 0,
      },
    },
  ],
  mostOrderedRestaurants: [
    { name: "Kyoto Sushi & Wok", count: 6, category: "Asian", image: "/img/card-2.png" },
    { name: "The Burger Joint", count: 4, category: "Fast Food", image: "/img/burger.jpg" },
    { name: "Green Bowl Oasis", count: 3, category: "Healthy", image: "/img/salad.jpg" },
  ],
  favorites: {
    restaurants: [
      {
        id: "luigis",
        name: "Luigi's Woodfire",
        badge: "-20% Today",
        category: "Italian - Fast Pizza",
        rating: "4.6 (2.1k)",
        location: "Little Italy",
        image: "/img/card-4.png",
      },
      {
        id: "poke",
        name: "Fresh Poke Bowls",
        badge: "15-20 min",
        category: "Healthy - Vegan",
        rating: "4.7 (430)",
        location: "Green Park Area",
        image: "/img/card-3.png",
      },
      {
        id: "burger-joint",
        name: "The Burger Joint",
        badge: "Free Delivery",
        category: "American - Fast Food",
        rating: "4.8 (1.2k)",
        location: "Downtown District",
        image: "/img/card-1.png",
      },
      {
        id: "bella-pasta",
        name: "La Bella Pasta",
        badge: "15-25 min",
        category: "Italian - Authentic",
        rating: "4.9 (2.3k)",
        location: "Historic District",
        image: "/img/card-6.png",
      },
    ],
    dishes: [
      {
        id: "truffle-burger",
        name: "Signature Truffle Burger",
        restaurant: "The Burger Joint",
        price: 14.99,
        description: "Black Angus beef, cheddar, smoked bacon, and truffle mayo.",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&q=80",
        category: "Fast Food",
      },
      {
        id: "green-bowl",
        name: "Green Bowl Oasis",
        restaurant: "Fresh Oasis",
        price: 15.99,
        description: "Quinoa, greens, edamame, avocado, and vinaigrette.",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&q=80",
        category: "Healthy",
      },
    ],
  },
  addresses: [
    {
      id: "home",
      title: "Home",
      street: "12 Green Park Area",
      apartment: "Apt. 48",
      city: "Kyiv",
      deliveryNote: "Call when outside.",
      phone: "+380 XX XXX XX XX",
      isDefault: true,
    },
    {
      id: "university",
      title: "University",
      street: "Main Campus, Building B",
      apartment: "",
      city: "Kyiv",
      deliveryNote: "Meet near the main entrance.",
      phone: "+380 XX XXX XX XX",
      isDefault: false,
    },
    {
      id: "work",
      title: "Work",
      street: "Business Center",
      apartment: "Floor 4",
      city: "Kyiv",
      deliveryNote: "Leave at reception.",
      phone: "+380 XX XXX XX XX",
      isDefault: false,
    },
  ],
  payments: [
    {
      id: "visa-4821",
      type: "Card",
      label: "Visa ending in 4821",
      maskedInfo: "•••• 4821",
      isDefault: true,
    },
    {
      id: "apple-pay",
      type: "Wallet",
      label: "Apple Pay",
      maskedInfo: "Connected",
      isDefault: false,
    },
  ],
  promoCodes: [
    {
      code: "STUDENT15",
      description: "15% off your next order",
      validUntil: "June 30",
      status: "available",
    },
    {
      code: "PIZZA20",
      description: "20% off selected pizza deals",
      validUntil: "Expired",
      status: "expired",
    },
  ],
  receipts: [
    { id: "DF-2035", restaurantName: "The Burger Joint", date: "May 24", total: 24.99 },
    { id: "DF-2018", restaurantName: "Luigi's Woodfire", date: "May 08", total: 17.99 },
  ],
  settings: {
    notifications: {
      orderUpdates: { email: true, push: true, sms: false },
      promotions: { email: true, push: false, sms: false },
      studentDiscounts: { email: true, push: true, sms: false },
      restaurantRecommendations: { email: false, push: true, sms: false },
      deliveryStatus: { email: true, push: true, sms: true },
    },
    foodPreferences: {
      cuisines: ["Asian", "Italian", "Healthy"],
      dietary: "No restrictions",
      spiceLevel: "Medium",
      priorities: ["Fast delivery", "Student discounts", "Healthy meals"],
    },
    language: "English",
    currency: "USD",
    connectedAccounts: [
      { name: "Google", status: "Connected" },
      { name: "Apple", status: "Not connected" },
      { name: "Facebook", status: "Not connected" },
      { name: "X", status: "Not connected" },
    ],
  },
  recommendations: [
    "Asian Cuisine",
    "Healthy & Diet",
    "Pizza Deals",
    "Student Discounts",
    "Fast Delivery Nearby",
  ],
};
