export const supportSummaryCards = [
  {
    label: "Open Tickets",
    value: "24",
    helper: "needs action",
    tone: "open",
  },
  {
    label: "New Tickets",
    value: "6",
    helper: "not reviewed yet",
    tone: "new",
  },
  {
    label: "High Priority",
    value: "5",
    helper: "urgent queue",
    tone: "high",
  },
  {
    label: "Overdue",
    value: "3",
    helper: "SLA missed",
    tone: "overdue",
  },
  {
    label: "Resolved Today",
    value: "18",
    helper: "closed cases",
    tone: "resolved",
  },
];

export const supportIssueTypeFilters = [
  "All issue types",
  "Account & profile",
  "Order or delivery",
  "Restaurant information",
  "Offer or discount",
  "Student Discount",
  "Payment or refund",
  "Technical problem",
  "Other",
  "Missing item",
  "Wrong item",
  "Late delivery",
  "Payment issue",
  "Refund request",
  "Restaurant issue",
  "Verification issue",
];

export const supportPriorityFilters = [
  "All priorities",
  "High",
  "Medium",
  "Low",
];

export const supportSlaFilters = [
  "All SLA",
  "On track",
  "Due soon",
  "Overdue",
];

export const supportStatusFilters = [
  "All",
  "New",
  "Open",
  "Waiting",
  "Resolved",
];

export const supportTicketsMockData = [
  {
    ticketId: "SUP-1044",
    requester: "Mia Wilson",
    source: "Customer",
    channel: "In-app chat",
    issueType: "Late delivery",
    summary: "Courier has not arrived yet",
    related: "Order #1044 • Pasta Point",
    priority: "High",
    status: "Open",
    sla: "Due soon",
    lastActivity: "12 min ago",
    lastActivityRank: 11,
    created: "Today, 10:24 AM",
    resolvedToday: false,
    linkedRecords: [
      ["Order", "#1044 — Pasta Point — On the way"],
      ["Customer", "Mia Wilson"],
      ["Restaurant", "Pasta Point"],
      ["Refund", "REF-1044 — Processing — $8.00"],
    ],
    conversation: [
      {
        author: "Customer",
        text: "My order is very late and the app still says it is on the way.",
      },
      { author: "System", text: "Order #1044 is marked as On the way." },
      {
        author: "Support note",
        text: "Courier delay detected. Refund request is processing.",
      },
    ],
    recommendedNextStep:
      "Check delivery status and send the customer an update.",
  },
  {
    ticketId: "SUP-1041",
    requester: "Lily Adams",
    source: "Customer",
    channel: "In-app chat",
    issueType: "Missing item",
    summary: "Customer says an item was missing",
    related: "Order #1041 • Green Bowl",
    priority: "Medium",
    status: "New",
    sla: "On track",
    lastActivity: "18 min ago",
    lastActivityRank: 9,
    created: "Today, 10:50 AM",
    resolvedToday: false,
    linkedRecords: [
      ["Order", "#1041 — Green Bowl — Delivered"],
      ["Customer", "Lily Adams"],
      ["Restaurant", "Green Bowl"],
      ["Refund", "REF-1041 — Requested — $22.30"],
    ],
    conversation: [
      {
        author: "Customer",
        text: "My salad bowl arrived without the extra chicken I paid for.",
      },
      { author: "System", text: "Order #1041 was delivered." },
      {
        author: "Support note",
        text: "Refund request created and waiting for review.",
      },
    ],
    recommendedNextStep:
      "Confirm the missing item and request refund review if eligible.",
  },
  {
    ticketId: "SUP-1042",
    requester: "Noah Clark",
    source: "System",
    channel: "System alert",
    issueType: "Payment issue",
    summary: "Payment failed but customer reports being charged",
    related: "Order #1042 • Quick Bites",
    priority: "High",
    status: "Open",
    sla: "Overdue",
    lastActivity: "38 min ago",
    lastActivityRank: 6,
    created: "Today, 9:58 AM",
    resolvedToday: false,
    linkedRecords: [
      ["Order", "#1042 — Quick Bites — Cancelled"],
      ["Transaction", "TXN-1042 — Failed"],
      ["Refund", "REF-1042 — Completed — $12.90"],
      ["Customer", "Noah Clark"],
    ],
    conversation: [
      { author: "System", text: "Payment failed for Order #1042." },
      {
        author: "Customer",
        text: "My bank shows the charge even though the order was cancelled.",
      },
      {
        author: "Support note",
        text: "Refund completed. Waiting to confirm customer sees reversal.",
      },
    ],
    recommendedNextStep: "Confirm transaction reversal and reply to the customer.",
  },
  {
    ticketId: "SUP-1037",
    requester: "Emma Brown",
    source: "Customer",
    channel: "Email",
    issueType: "Wrong item",
    summary: "Customer received the wrong pizza",
    related: "Order #1037 • Pizza Nova",
    priority: "Medium",
    status: "Resolved",
    sla: "On track",
    lastActivity: "Yesterday",
    lastActivityRank: 1,
    created: "Yesterday",
    resolvedToday: false,
    linkedRecords: [
      ["Order", "#1037 — Pizza Nova — Delivered"],
      ["Customer", "Emma Brown"],
      ["Restaurant", "Pizza Nova"],
      ["Refund", "REF-1037 — Rejected — $15.00"],
    ],
    conversation: [
      { author: "Customer", text: "I ordered a veggie pizza but received pepperoni." },
      {
        author: "Restaurant",
        text: "The kitchen confirmed the correct item was prepared.",
      },
      {
        author: "Support note",
        text: "Refund rejected after restaurant confirmation.",
      },
    ],
    recommendedNextStep: "No action needed. Ticket is resolved.",
  },
  {
    ticketId: "SUP-1048",
    requester: "Alex Carter",
    source: "Customer",
    channel: "In-app chat",
    issueType: "Late delivery",
    summary: "Customer asks why the order is still preparing",
    related: "Order #1048 • Burger House",
    priority: "High",
    status: "New",
    sla: "Due soon",
    lastActivity: "8 min ago",
    lastActivityRank: 12,
    created: "Today, 10:42 AM",
    resolvedToday: false,
    linkedRecords: [
      ["Order", "#1048 — Burger House — Preparing"],
      ["Customer", "Alex Carter"],
      ["Restaurant", "Burger House"],
      ["Refund", "No linked refund."],
    ],
    conversation: [
      {
        author: "Customer",
        text: "My order has been preparing for too long. Can you check it?",
      },
      { author: "System", text: "Order #1048 is still Preparing." },
      { author: "Support note", text: "Restaurant response needed." },
    ],
    recommendedNextStep: "Request a restaurant update and reply to the customer.",
  },
  {
    ticketId: "SUP-1046",
    requester: "David Kim",
    source: "Customer",
    channel: "In-app chat",
    issueType: "Verification issue",
    summary: "Student verification is still pending",
    related: "Student verification • David Kim",
    priority: "Low",
    status: "Waiting for customer",
    sla: "On track",
    lastActivity: "1h ago",
    lastActivityRank: 4,
    created: "Today, 10:34 AM",
    resolvedToday: false,
    linkedRecords: [
      ["Customer", "David Kim"],
      ["Student status", "Pending"],
      ["Discount", "Student Deal — Pending verification"],
      ["Order", "No linked order."],
    ],
    conversation: [
      {
        author: "Customer",
        text: "I uploaded my student document but it still says pending.",
      },
      { author: "Support", text: "Please upload a clearer photo of your student ID." },
      { author: "Support note", text: "Waiting for customer response." },
    ],
    recommendedNextStep: "Wait for customer document update.",
  },
  {
    ticketId: "SUP-203",
    requester: "Burger House",
    source: "Restaurant",
    channel: "Restaurant portal",
    issueType: "Restaurant issue",
    summary: "Restaurant tablet is offline",
    related: "Burger House • Availability",
    priority: "High",
    status: "Waiting for restaurant",
    sla: "Due soon",
    lastActivity: "22 min ago",
    lastActivityRank: 8,
    created: "Today, 10:12 AM",
    resolvedToday: false,
    linkedRecords: [
      ["Restaurant", "Burger House"],
      ["Availability", "Paused"],
      ["Issue", "Tablet offline"],
      ["Order", "No linked order."],
    ],
    conversation: [
      { author: "Restaurant", text: "Our tablet stopped receiving new orders." },
      { author: "System", text: "Burger House availability changed to Paused." },
      { author: "Support", text: "Please confirm if the device is back online." },
    ],
    recommendedNextStep:
      "Send restaurant reminder and confirm availability before resuming orders.",
  },
  {
    ticketId: "SUP-1038",
    requester: "Daniel Lee",
    source: "Customer",
    channel: "In-app chat",
    issueType: "Wrong item",
    summary: "Customer received the wrong taco order",
    related: "Order #1038 • Taco Street",
    priority: "Medium",
    status: "Waiting for restaurant",
    sla: "On track",
    lastActivity: "45 min ago",
    lastActivityRank: 5,
    created: "Yesterday",
    resolvedToday: false,
    linkedRecords: [
      ["Order", "#1038 — Taco Street — Delivered"],
      ["Customer", "Daniel Lee"],
      ["Restaurant", "Taco Street"],
      ["Refund", "No linked refund."],
    ],
    conversation: [
      { author: "Customer", text: "I received beef tacos instead of veggie tacos." },
      { author: "Support", text: "We contacted the restaurant to confirm the order." },
      { author: "Support note", text: "Waiting for restaurant response." },
    ],
    recommendedNextStep: "Send restaurant reminder if no response is received soon.",
  },
  {
    ticketId: "SUP-1045",
    requester: "Sofia Miller",
    source: "Customer",
    channel: "In-app chat",
    issueType: "Refund request",
    summary: "Customer asks for partial refund",
    related: "Order #1045 • Sushi Corner",
    priority: "Medium",
    status: "Open",
    sla: "On track",
    lastActivity: "26 min ago",
    lastActivityRank: 7,
    created: "Today, 10:21 AM",
    resolvedToday: false,
    linkedRecords: [
      ["Order", "#1045 — Sushi Corner — Delivered"],
      ["Customer", "Sofia Miller"],
      ["Restaurant", "Sushi Corner"],
      ["Refund", "No linked refund."],
    ],
    conversation: [
      { author: "Customer", text: "One sushi roll was missing. Can I get a partial refund?" },
      { author: "System", text: "Order #1045 was delivered." },
      { author: "Support note", text: "Refund eligibility needs review." },
    ],
    recommendedNextStep: "Review refund eligibility and request refund review if needed.",
  },
  {
    ticketId: "SUP-1049",
    requester: "Olivia Stone",
    source: "Customer",
    channel: "In-app chat",
    issueType: "Verification issue",
    summary: "Student deal is not applying",
    related: "Student verification • Olivia Stone",
    priority: "Low",
    status: "New",
    sla: "On track",
    lastActivity: "5 min ago",
    lastActivityRank: 13,
    created: "Today",
    resolvedToday: false,
    linkedRecords: [
      ["Customer", "Olivia Stone"],
      ["Student status", "Pending"],
      ["Discount", "Student Deal — Pending verification"],
      ["Transaction", "No linked transaction."],
    ],
    conversation: [
      {
        author: "Customer",
        text: "I cannot use the student discount even though I uploaded my document.",
      },
      { author: "System", text: "Student verification status is Pending." },
      { author: "Support note", text: "Verification review needed." },
    ],
    recommendedNextStep:
      "Check student verification status and request clearer document if needed.",
  },
  {
    ticketId: "SUP-1050",
    requester: "Mark King",
    source: "Customer",
    channel: "Email",
    issueType: "Refund request",
    summary: "Customer asked about refund status",
    related: "Order #1039 • Sushi Corner",
    priority: "Low",
    status: "Resolved",
    sla: "On track",
    lastActivity: "Today, 9:20 AM",
    lastActivityRank: 10,
    created: "Today, 8:50 AM",
    resolvedToday: true,
    linkedRecords: [
      ["Order", "#1039 — Sushi Corner — Delivered"],
      ["Customer", "Mark King"],
      ["Restaurant", "Sushi Corner"],
      ["Refund", "REF-1039 — Completed — $9.60"],
    ],
    conversation: [
      { author: "Customer", text: "Can you confirm if my refund was completed?" },
      {
        author: "Support",
        text: "Your refund has been completed and should appear on your card shortly.",
      },
      {
        author: "Support note",
        text: "Ticket resolved after refund confirmation.",
      },
    ],
    recommendedNextStep: "No action needed. Ticket is resolved.",
  },
  {
    ticketId: "SUP-1051",
    requester: "Pasta Point",
    source: "System",
    channel: "System alert",
    issueType: "Restaurant issue",
    summary: "Partner response is blocking an active delivery case",
    related: "Pasta Point • Late delivery follow-up",
    priority: "High",
    status: "Open",
    sla: "Overdue",
    lastActivity: "52 min ago",
    lastActivityRank: 3,
    created: "Today, 9:35 AM",
    resolvedToday: false,
    linkedRecords: [
      ["Restaurant", "Pasta Point"],
      ["Order", "#1044 — Pasta Point — On the way"],
      ["Customer", "Mia Wilson"],
      ["Refund", "REF-1044 — Processing — $8.00"],
    ],
    conversation: [
      {
        author: "System",
        text: "Restaurant follow-up is overdue for the late delivery case.",
      },
      {
        author: "Support note",
        text: "Partner context is needed before sending the final customer update.",
      },
    ],
    recommendedNextStep:
      "Request restaurant update and then send Mia Wilson a clear delivery status.",
  },
];
